default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        language_version: python3.10
        name: end-of-file-fixer
        description: Ensure a newline at the end of the file
        stages: [commit]

      - id: trailing-whitespace
        language_version: python3.10
        name: trailing-whitespace
        description: Remove trailing whitespaces
        stages: [commit]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.2.2"
    hooks:
      - id: ruff
        language_version: python3.10
        name: ruff
        types: [python]
        args: [--fix, --config, pyproject.toml]

      - id: ruff-format
        language_version: python3.10
        name: ruff-format
        types: [python]
        args: [--config, pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        language_version: python3.10
        stages: [commit]

  - repo: https://github.com/zricethezav/gitleaks
    rev: "v8.18.1"
    hooks:
      - id: gitleaks
        language_version: python3.10
        name: "gitleaks"
