[tool.kedro]
package_name = "registry"
project_name = "Automated Insta"
kedro_init_version = "0.19.3"
tools = ['Linting', 'Testing', 'Custom Logging', 'Documentation', 'Data Structure']
example_pipeline = "True"
source_dir = "src"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/auto_insta -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff]
line-length = 88
show-fixes = true
lint.select = [
    "F",   # Pyflakes
    "W",   # pycodestyle
    "E",   # pycodestyle
    "I",   # isort
    "UP",  # pyupgrade
    "PL",  # Pylint
    "T201", # Print Statement
]
lint.ignore = ["E501"]  # Ruff format takes care of line-too-long
