[tool.kedro]
package_name = "registry"
project_name = "Automated Insta"
kedro_init_version = "0.19.3"
tools = ['Linting', 'Testing', 'Custom Logging', 'Documentation', 'Data Structure']
example_pipeline = "True"
source_dir = "src"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/auto_insta -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.ruff]
exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".pytype",
    ".ruff_cache",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "tools",
    ".github",
    "test_*.py",
    "conftest.py",
    "src/*/__main__.py"
]
target-version = "py39"
indent-width = 4

[tool.ruff.format]
quote-style = "double" # Like Black, use double quotes for strings.
indent-style = "space" # Like Black, indent with spaces, rather than tabs.
skip-magic-trailing-comma = false
line-ending = "auto" # Like Black, automatically detect the appropriate line ending.

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

# Ruff Lint
[tool.ruff.lint]
ignore-init-module-imports = true
select = [
    "A", # builtin-variable-shadowing
    "ARG", # flake8-unused-arguments
    "B", # flake8-bugbear
    "C", # flake8-comprehensions
    "D", # pydocstyle
    "E", # pycodestyle errors
    "FLY", # flynt
    "G", # flake8-logging-format
    "N", # pep8-naming
    "PGH", # pygrep-hooks
    "PL", # pylint
    "W", # pycodestyle warnings
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "SLF", # flake8-self
]
