canvas_settings:
  image_width: 1080
  image_length: 1080
  background_color: 255

text_settings:

final_image:
  font_location: ./data/01_raw/font.ttf
  margin_percentage: 0.1
  line_length_percentage: 0.8
  font_color: (0, 0, 0)
  font_size: 60
