name: Main workflow

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and run pre-commit
        run: |
          make check-end-of-file-fixer
          make check-gitleaks
          make check-prettier
          make check-ruff
          make check-trailing-whitespace
