name: Main workflow

on:
  push:
    branches:
      - "**"

jobs:
  ##################################################################################################
  ############### CHECKS ###########################################################################
  ##################################################################################################

  run_checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          [
            "make check-end-of-file-fixer",
            "make check-gitleaks",
            "make check-legal",
            "make check-nbstripout",
            "make check-prettier",
            "make check-ruff",
            "make check-trailing-whitespace",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
