name: Main workflow

on: [push]

jobs:
  run-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # This step checks out a copy of your repository.

      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y make
        # This step ensures the `make` utility is installed on the runner.

      - name: Execute Makefile commands
        run: |
          make check-end-of-file-fixer
          make check-gitleaks
          make check-prettier
          make check-ruff
          make check-trailing-whitespace
